F24413 support french/italian for ArtikelstammImport
elexis/elexis-3-base pull request #241
Opened 2022-08-13 16:23 UTC by ngiger

Will only import french/italian when using an artikelstamm generated via https://github.com/ngiger/oddb2xml/tree/italian.

Will create a PR for https://github.com/ngiger/oddb2xml/tree/italian only if this PR gets merged.

This PR is backward compatible.

Missing is support for ATC-Codes in french and italian, but I do not know yet, howto handle this

2022-08-15 07:37 UTC, huthomas requested changes

2022-08-15 07:37 UTC, huthomas commented on bundles/at.medevit.ch.artikelstamm.model/META-INF/MANIFEST.MF
> + ch.elexis.core.data;bundle-version="3.10.0"
Import bitte wieder entfernen, local config sollte nicht über CoreHub ausgelesen werden. Siehe weitere Kommentare.

2022-08-15 07:37 UTC, huthomas commented on bundles/at.medevit.ch.artikelstamm.model/src/at/medevit/ch/artikelstamm/model/importer/ArtikelstammImporter.java
> +				String lang = ch.elexis.core.data.activator.CoreHub.localCfg.get(Preferences.ABL_LANGUAGE, "d");
Auf die local config sollte mit dem ConfigService zugegriffen werden.
```
import ch.elexis.core.services.holder.ConfigServiceHolder;

ConfigServiceHolder.get().getLocal(Preferences.ABL_LANGUAGE, "d");
```

2022-08-15 07:37 UTC, huthomas commented on bundles/at.medevit.ch.artikelstamm.model/src/at/medevit/ch/artikelstamm/model/importer/ArtikelstammImporter.java
> +		String lang = ch.elexis.core.data.activator.CoreHub.localCfg.get(Preferences.ABL_LANGUAGE, "d");
Auf die local config sollte mit dem ConfigService zugegriffen werden.

2022-08-15 07:37 UTC, huthomas commented on tests/at.medevit.ch.artikelstamm.model.test/src/at/medevit/ch/artikelstamm/model/importer/ArtikelstammImporterTest.java
> +		ch.elexis.core.data.activator.CoreHub.localCfg.set(Preferences.ABL_LANGUAGE, lang);
Auf die local config sollte mit dem ConfigService zugegriffen werden.

2022-08-15 07:37 UTC, huthomas commented on tests/at.medevit.ch.artikelstamm.model.test/src/at/medevit/ch/artikelstamm/model/importer/ArtikelstammImporterTest.java
> +		ch.elexis.core.data.activator.CoreHub.localCfg.set(Preferences.ABL_LANGUAGE, "d");
Auf die local config sollte mit dem ConfigService zugegriffen werden.

2022-09-08 15:12 UTC, ngiger commented on tests/at.medevit.ch.artikelstamm.model.test/src/at/medevit/ch/artikelstamm/model/importer/ArtikelstammImporterTest.java
> +		ch.elexis.core.data.activator.CoreHub.localCfg.set(Preferences.ABL_LANGUAGE, lang);
Aber wie macht man das? Ich sehe im ConfigService keine setLocal, nur ein setGlobal und das ist deprecated?

2022-09-08 15:20 UTC, ngiger commented on tests/at.medevit.ch.artikelstamm.model.test/src/at/medevit/ch/artikelstamm/model/importer/ArtikelstammImporterTest.java
> +		ch.elexis.core.data.activator.CoreHub.localCfg.set(Preferences.ABL_LANGUAGE, lang);
Ist es richtig, dass ABLAUF als localCfg gespeichert wird. Wäre es nicht korrekt, dies als global zu behandeln, da diese Sprache ja für die gesamte DB und ALLE Anwender gelten soll, wenn wir keine Probleme bekommen wollen?

2022-09-08 16:40 UTC, huthomas approved these changes

2022-09-08 16:41 UTC, merged