25624 titel umbenennen von bestellung auf bereich
elexis/elexis-3-base pull request #272
Opened 2023-09-12 15:22 UTC by victoriacarola

2023-09-13 08:25 UTC, col-panic requested changes

2023-09-13 08:25 UTC, col-panic commented on bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/composite/SideBarComposite.java
> +		label.setText("Bereiche");
Das wollen wir eigentlich nicht! Du ersetzt einen internationalisierten String durch einen statischen String - wenn die Überseztung nicht passen ist, bitte die bestehende ändern oder eine neue machen

2023-09-13 08:25 UTC, col-panic commented on bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/composite/SideBarComposite.java
> +						Boolean.toString(scrollToNowCheck.getSelection()));
Bitte keine formattierungsänderungen

2023-10-18 07:49 UTC, huthomas commented
Bitte hier die Änderung auch so anpassen wie in https://github.com/elexis/elexis-3-base/pull/283 .

2023-10-23 08:30 UTC, huthomas commented
Die Änderung wurde bereits mit https://github.com/elexis/elexis-3-base/pull/276 in den master übernommen.

2023-10-23 08:30 UTC, closed without merging