[25513] Image Erweiterung implementiert für MoleMax
elexis/elexis-3-base pull request #275
Opened 2023-09-21 11:49 UTC by Daksic28

Ich habe die Erweiterung soweit fertiggestellt. Lediglich die Drag-and-drop-Scroll-Funktion habe ich noch nicht umsetzen können, aber ich bleibe dran. Ich würde mich über jegliches Feedback und Tipps freuen, insbesondere wo und was ich noch verbessern kann.

2023-10-11 08:32 UTC, col-panic requested changes

2023-10-11 08:32 UTC, col-panic commented on bundles/ch.elexis.molemax/.classpath
> +	</classpathentry>
Das ist nicht gut - hier änderst du die Build-Einstellungen in dem du das Java Moduling aktivierst,
bitte das wieder rausnehmen!

2023-10-11 08:32 UTC, col-panic commented on bundles/ch.elexis.molemax/.classpath
> +	<classpathentry exported="true" kind="lib" path="lib/org.eclipse.nebula.widgets.gallery_1.0.0.202303072132.jar" sourcepath="lib/org.eclipse.nebula.widgets.gallery.source_1.0.0.202303072132.jar"/>
exportieren solltest du das eigentlich nicht, das ist nur für die verwendung in deinem plugin.
Bei nächsten Target-Update werden wir das ins Target selbst aufnehmen https://redmine.medelexis.ch/issues/23378

2023-10-11 08:32 UTC, col-panic commented on bundles/ch.elexis.molemax/src/ch/elexis/molemax/data/Tracker.java
> +		return ret.toString();
Bitte noch löschen das system.out

2023-10-11 08:32 UTC, col-panic commented on bundles/ch.elexis.molemax/META-INF/MANIFEST.MF
>  Bundle-Version: 3.9.0.qualifier
Du solltest die Version des Plugin erhöhen! Hier kommt neue Funktionalität rein,
mach 3.10.0.qualifier draus. Du musst dann auch enstprechend das feature in der Version erhöhen.

2023-10-16 07:09 UTC, Daksic28 commented
Hab das Feedback umgesetzt und Leerzeilen auch überall gelöscht

2023-10-16 07:13 UTC, merged