[25736] E-mail dispatch option in the appointment creation dialog
elexis/elexis-3-base pull request #280
Opened 2023-10-13 13:48 UTC by Daksic28

2023-10-16 08:49 UTC, huthomas requested changes

2023-10-16 08:49 UTC, huthomas commented on bundles/at.medevit.elexis.agenda.ui/META-INF/MANIFEST.MF
> + ch.elexis.core.mail.ui.client,
Wenn die mail über das mail senden command versendet wird, wären die Abhängigkeiten zu `ch.elexis.core.mail.ui.handlers` nicht nötig?

Für die Konfiguration des mail account wird immer` ch.elexis.core.mail.ui.client` benötigt.

2023-10-16 08:49 UTC, huthomas commented on bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/handler/EmailSender.java
> +		});
Was fehlt beim mail senden command das dieser code nötig ist?

2023-10-16 08:49 UTC, huthomas commented on bundles/ch.elexis.agenda/src/ch/elexis/agenda/preferences/AgendaDefinitionPreferencePage.java
> +	private ComboViewer appointmentTemplatesViewer, accountsViewer;
Bitte alle Felder in eine eigene Zeile.

2023-10-16 08:49 UTC, huthomas commented on bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/handler/EmailSender.java
> +				: savedAccount;
Hier würde ein if StringUtils.isEmpty(savesAccount) den code leserlicher machen.

2023-10-16 08:49 UTC, huthomas commented on bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/composite/AppointmentDetailComposite.java
> +		    }
Weshalb wird hier der selektierte Patient in Elexis gesetzt?

Das Verändert den workflow in Elexis. Ist das Absicht?

2023-10-16 08:49 UTC, huthomas commented on bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/composite/AppointmentDetailComposite.java
> +	public void setCompTimeToModel() {
Weshalb wird die Methode public?

2023-10-16 08:49 UTC, huthomas commented on bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/composite/AppointmentDetailComposite.java
>  	private Combo comboArea;
Am besten wäre es ein eigenes Composite für die mail Funktionalität zu machen, und das dann hier auf dem AppointmentDetailComposite zu verwenden.

So ist der Code vermischt, und es wird schwierig ein AppointmentDetailComposite ohne email Funktionalität dar zu stellen.

2023-10-16 11:48 UTC, huthomas commented on bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/handler/EmailSender.java
> +		});
Beispiel für einen eigenen Context für die Textersetzung aus AppointmentReminderIdentifiedRunnableUtil.
<pre>
IContext context = contextService.createNamedContext("appointment_reminder_context");
context.setTyped(appointment);
context.setTyped(selectedPatient);
String _message = textReplacementService.performReplacement(context, messageTemplate);
</pre>

2023-10-17 13:33 UTC, Daksic28 commented
Habe dein Feedback umgesetzt, habe ein neues EmailComposite programmiert und den EmailSender so bearbeitet, dass er über Commands funktioniert.

2023-10-18 08:06 UTC, huthomas requested changes

2023-10-18 08:06 UTC, huthomas commented on bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/composite/EmailComposit.java
> +public class EmailComposit extends Composite {
Bitte in EmailComposite umbenennen.

2023-10-18 08:06 UTC, huthomas commented on bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/composite/AppointmentDetailComposite.java
> +	}
Können diese Methoden auch alle auf das EmailComposite verschoben werden?

2023-10-18 08:06 UTC, huthomas commented on bundles/at.medevit.elexis.agenda.ui/src/at/medevit/elexis/agenda/ui/dialog/AppointmentDialog.java
> +
Bitte entfernen wenn das nicht verwendet wird.

2023-10-19 08:23 UTC, Daksic28 commented
Hab das besprochene umgesetzt so gut es geht hab jetzt nur 2 Geter in AppointmentDetailComposite

2023-10-27 08:51 UTC, merged