3.10
elexis/elexis-3-base pull request #312
Opened 2024-02-01 15:23 UTC by victoriacarola

2024-02-05 09:22 UTC, huthomas requested changes

2024-02-05 09:22 UTC, huthomas commented on bundles/ch.elexis.agenda/src/ch/elexis/agenda/ui/AgendaParallel.java
> +		}
In AgendaWeek (unteres file) werden die messages verwendet, und hier nicht. Bitte hier auch die dafür im core angelegten messages verwenden.

2024-02-05 09:24 UTC, huthomas commented
Unabhängig von dem obigen Kommentar noch die Frage weshalb dieser pull request gegen 3.10 geht und nicht gegen den master?

2024-04-17 07:06 UTC, col-panic commented
@victoriacarola @huthomas ist das noch relevant, ansonsten bitte schliessen!

2024-04-17 10:46 UTC, merged