[26233] LG1 laboratory order creation via the medicalvalues api
elexis/elexis-3-base pull request #317
Opened 2024-03-07 13:18 UTC by MKmedicalvalues

The code is mostly copied from the already existing laboratory order plugin for LG1, since we only needed to change the action that will be performed which is a smiple http call to our order creation api with the corresponding query parameters extracted from the patient and encounter objects.

2024-03-11 07:11 UTC, col-panic requested changes
Bitte eine kurze Dokumentation zu dem Plugin hinzufügen (e.g. `doc/readme.md`), was, wofür, wie einrichten, wie verwenden. Danke!

2024-03-11 07:11 UTC, col-panic commented on bundles/ch.elexis.labororder.lg1_medicalvalues/src/ch/elexis/labororder/lg1_medicalvalues/order/LabOrderAction.java
> +import ch.elexis.data.Patient;
Dies ist das alte Modell! Bitte Neu-Funktionalität auf base `ch.elexis.core.model.IPatient` entwickeln.

2024-03-11 07:11 UTC, col-panic commented on bundles/ch.elexis.labororder.lg1_medicalvalues/src/ch/elexis/labororder/lg1_medicalvalues/order/LabOrderAction.java
> +				Desktop.getDesktop().browse(uri);
Könnte anstatt `java.awt.Desktop` hier auch `IWorkbenchBrowserSupport browserSupport = PlatformUI.getWorkbench().getBrowserSupport();` verwendet werden?

2024-03-11 07:11 UTC, col-panic commented on bundles/ch.elexis.labororder.lg1_medicalvalues/src/ch/elexis/labororder/lg1_medicalvalues/order/LabOrderAction.java
> +		URIBuilder builder = new URIBuilder("https://oe.lg1.lan/mdi/orders/importPatientAndCreateOrder");
Ich bin mit dem Plugin nicht vertraut, wie wird sichergestellt, dass diese URL erreichbar ist? Wird das
auf jeder Station manuell eingetragen?

2024-03-11 07:11 UTC, col-panic commented on bundles/ch.elexis.labororder.lg1_medicalvalues/src/ch/elexis/labororder/lg1_medicalvalues/order/model/Patient.java
> +                Pattern pattern = Pattern.compile("^([A-Za-z-ß\\s]+)(\\d+)$");
Wäre gut, wenn man das ins Field nehmen würde, dann wirds nur einmal initialisiert.

2024-03-11 07:11 UTC, col-panic commented on bundles/ch.elexis.labororder.lg1_medicalvalues/src/ch/elexis/labororder/lg1_medicalvalues/order/model/Patient.java
> +		if (fall != null && fall.getPatient() != null && !patient.getId().equals(fall.getPatient().getId())) {
Bitte über  `ICoverage` gehen. `Fall` ist deprecated. Hier analog wie oben über den IContextService

2024-03-11 12:46 UTC, MKmedicalvalues commented on bundles/ch.elexis.labororder.lg1_medicalvalues/src/ch/elexis/labororder/lg1_medicalvalues/order/LabOrderAction.java
> +		URIBuilder builder = new URIBuilder("https://oe.lg1.lan/mdi/orders/importPatientAndCreateOrder");
Ja genau. Die URL muss auf jeder Station an der das Plugin verwendet werden soll erreichbar sein. Das wird dann von LG1 oder medicalvalues entsprechend konfiguriert werden.

2024-03-13 06:58 UTC, col-panic commented on bundles/ch.elexis.labororder.lg1_medicalvalues/rsc/docsPluginLocation.png
Die Location ist nicht so gut - siehe META-INF/MANIFEST.MF; der inhalt von `rsc/` wird im kompilierten jar
mitgegeben. Also auch dieses Bild hier. Bitte in `/doc` verschieben!

2024-03-13 07:01 UTC, col-panic requested changes
Nice! Bitte noch das docsPluginLocation verschieben, siehe comment!

2024-03-13 08:02 UTC, MKmedicalvalues commented on bundles/ch.elexis.labororder.lg1_medicalvalues/rsc/docsPluginLocation.png
Ah okay, alles klar : > Wurde verschoben.

2024-03-13 13:20 UTC, merged